Models/ErrorViewModel.cs
namespace monozd.Models;

public class ErrorViewModel
{
    public string RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/VehicleContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;

using System.Linq;
using System.Threading.Tasks;

namespace monozd.Models
{
    public class VehicleContext : DbContext
    {
        public DbSet<VehicleModel> Models { get; set;}
        public DbSet<VehicleMake> Makers { get; set; }
        
        protected override void OnConfiguring(DbContextOptionsBuilder options)
        => options.UseSqlite(@"Data Source=/home/nsikic/monozd/Vehicle.db");
    }
}

Models/VehicleMake.cs
using System.ComponentModel.DataAnnotations;

namespace monozd.Models
{
    public class VehicleMake
    {

    
    public int Id { get; set; }
    [Required(ErrorMessage ="Please enter a name")]
    public string Name { get; set; }
    [Required(ErrorMessage ="Please enter an abrivation")]
    public string Abrv { get; set; }

    }

}

Models/VehicleModel.cs
using System.ComponentModel.DataAnnotations;

namespace monozd.Models
{
    public class VehicleModel
    {

    
    public int Id { get; set; }
    [Required(ErrorMessage ="Please enter Manufacturer's ID")]
    public int MakeId { get; set; }
    [Required(ErrorMessage ="Please enter name")]
    public string Name { get; set; }
    [Required(ErrorMessage ="Please enter an abrivation")]
    public string Abrv { get; set; }

    }

}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using monozd.Models;

namespace monozd.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }

}

Controllers/VehicleMakeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using monozd.Models;
namespace monozd.Controllers;

public class VehicleMakeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public VehicleMakeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }

    public IActionResult CreateVehicleMake()
    {
        List<VehicleMake> manufacturers = new List<VehicleMake>();

        using(var db = new VehicleContext())
        {
            manufacturers = db.Makers.ToList();
        }

        TempData["manufacturers"] = manufacturers;
        return View();
    }



    [HttpPost]
    public IActionResult CreateVehicleMake(VehicleMake manufacturer)
    {
        if(ModelState.IsValid)
        {
        using (var db = new VehicleContext())
            {
            db.Add(manufacturer);
            db.SaveChanges();
            }
        }
        return View();
        
    }

    public IActionResult SearchManufacturer(string searchTerm)
    {
        List<VehicleMake> manufacturers = new List<VehicleMake>();

        using(var db = new VehicleContext())
        {
            manufacturers = db.Makers.Where(u => u.Name.ToLower().Contains(searchTerm.ToLower())).ToList();        }

        TempData["manufacturers"] = manufacturers;

        return View("CreateVehicleMake");
    }

    [HttpPost]
    public IActionResult UpdateManufacturer(VehicleMake manufacturer)
    {
        using (var db = new VehicleContext())
        {
            var manufacturerDb  = db.Makers.Where(u => u.Id == manufacturer.Id).FirstOrDefault();
            TempData["manufacturerDb"] = manufacturerDb;


        }

        return View();
    }

    public IActionResult UpdateManufacturerFinal(VehicleMake manufacturer)
    {
        using (var db = new VehicleContext())
        {
            var manufacturerDb = db.Makers.Where(u =>u.Id == manufacturer.Id).FirstOrDefault();

            manufacturerDb.Name = manufacturer.Name;
            manufacturerDb.Abrv = manufacturer.Abrv;

            db.SaveChanges();
        }

        return View("CreateVehicleMake");
    }

    [HttpPost]
    public IActionResult DeletePost(int id)
    {   
        using (var db = new VehicleContext())
        {
        var manufacturerDb = db.Makers.Find(id);
        
        if(manufacturerDb == null || id == 0)
        {
            return NotFound();
        }    
        
        db.Makers.Remove(manufacturerDb);
        db.SaveChanges();
        
        }
        return RedirectToAction("CreateVehicleMake");
    }
    public IActionResult Delete(int id)
    {
        if(id == 0)
        {
            return NotFound();
        }
        using (var db = new VehicleContext())
        {
        var manufacturerDb = db.Makers.Find(id);

        db.Makers.Remove(manufacturerDb);
        db.SaveChanges();

        }


        return View("CreateVehicleMake");
    }


}

Controllers/VehicleModelController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using monozd.Models;

namespace monozd.Controllers;

public class VehicleModelController : Controller
{
    private readonly ILogger<VehicleModelController> _logger;

    public VehicleModelController(ILogger<VehicleModelController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }

    public IActionResult CreateVehicleModel()
    {
        List<VehicleModel> models = new List<VehicleModel>();
        
        using(var db = new VehicleContext())
        {
            models = db.Models.ToList();
        }
        TempData["models"] = models;
        return View();
    }

    [HttpPost]
    public IActionResult CreateVehicleModel(VehicleModel model)
    {   
        if(ModelState.IsValid)
        {
        using (var db = new VehicleContext())
            {
            db.Add(model);
            db.SaveChanges();
            }
        }
        return View();
    }

    public IActionResult SearchModel(string searchTerm)
   {
        List<VehicleModel> models = new List<VehicleModel>();

        using(var db = new VehicleContext())
        {
            models = db.Models.Where(u => u.Name.ToLower().Contains(searchTerm.ToLower())).ToList();
        }

        TempData["models"] = models;
        return View("CreateVehicleModel");
    }


      [HttpPost]
    public IActionResult UpdateModel(VehicleModel model)
    {
        using (var db = new VehicleContext())
        {
            var modelDb  = db.Models.Where(u => u.Id == model.Id).FirstOrDefault();
            TempData["modelDb"] = modelDb;
            
        }

        return View();
    }

    public IActionResult UpdateModelFinal(VehicleModel model)
    {
        using (var db = new VehicleContext())
        {
            var UpdateModel = db.Models.Where(u =>u.Id == model.Id).FirstOrDefault();

            UpdateModel.MakeId = model.MakeId;
            UpdateModel.Name = model.Name;
            UpdateModel.Abrv = model.Abrv;

            db.SaveChanges();
        }
        return View("CreateVehicleModel");
    }

    [HttpPost]
    public IActionResult DeletePost(int id)
    {   
        using (var db = new VehicleContext())
        {
        var modelsDb = db.Models.Find(id);
        
        if(modelsDb == null || id == 0)
        {
            return NotFound();
        }    
        
        db.Models.Remove(modelsDb);
        db.SaveChanges();
        
        }
        return RedirectToAction("CreateVehicleModel");
    }
    public IActionResult Delete(int id)
    {
        if(id == 0)
        {
            return NotFound();
        }
        using (var db = new VehicleContext())
        {
        var modelsDb = db.Models.Find(id);

        db.Models.Remove(modelsDb);
        db.SaveChanges();

        }


        return View("CreateVehicleMake");
    }

}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - monozd</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/monozd.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">monozd</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="VehicleMake" asp-action="CreateVehicleMake">Manufacturers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="VehicleModel" asp-action="CreateVehicleModel">Car models</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - monozd - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/VehicleMake/CreateVehicleMake.cshtml
@model monozd.Models.VehicleMake
@{
    ViewData["Title"] = "CreateVehicleMake";

    List<VehicleMake> manufacturers  = TempData["manufacturers"] as List<VehicleMake>;
}

    <div class="container">
    <form action="/vehiclemake/createvehiclemake" method="post">
        <div class="form-group">
            <label>Name</label>
            <input type="Name" placeholder="Enter Manufacturer name " asp-for="Name">
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label>Abrv</label> 
            <input type="Abrv" placeholder="Enter Manufacturer abrivation " asp-for="Abrv">
            <span asp-validation-for="Abrv" class="text-danger"></span>

        <button type="submit" class="btn btn-primary">Submit</button>
    </form>

    </div>

    <div class="container">

        @if(manufacturers != null && manufacturers.Count >= 1)
        {

        
        <form from action="/VehicleMake/SearchManufacturer" method="post">
            <div class="form-group">
                <label>Search</label>
                <input type="text" name="searchTerm"/>
            </div> 
            <button type="submit" class="btn btn-primary">Search</button>
        </form>   
<table class="table table-dark">
  <thead>
    <tr>
      <th scope="col">#Id</th>
      <th scope="col">Name</th>
      <th scope="col">Abrv</th>
    </tr>
  </thead>
  <tbody>
      @foreach (var vehicles in manufacturers)
      {
        <tr>
      <td>@vehicles.Id</td>
      <td>@vehicles.Name</td>
      <td>@vehicles.Abrv</td>
      <td>
          <form asp-action="UpdateManufacturer" asp-controller="VehicleMake" method="post">
              <input type="hidden" asp-for="Id" value="@vehicles.Id" />
              <button type="submit"  class="btn btn-success">Update</button>
          </form>
          <form asp-action="DeletePost" asp-controller="VehicleMake" method="post">
              <input type="hidden" asp-for="Id" value="@vehicles.Id" />
              <button type="Delete" class="btn btn-danger">Delete</button>
          </form>
      </td>
    </tr>
      }
    
  </tbody>
</table>
        }
    </div>
    

Views/VehicleMake/DeletePost.cshtml
@model monozd.Models.VehicleMake
@{
    ViewData["Title"] = "DeleteManufacturer";
    VehicleMake manufacturer = TempData["manufacturerDb"] as VehicleMake;

}

<h1>Delete Manufacturer</h1>

    <div class="container">
    <form asp-action="DeletePost" method="post" asp-controllesr="VehicleMake" >
    <input type ="hidden" asp-for="Id" value="@manufacturer.Id"/>
        <button type="submit" class="btn btn-danger">Delete</button>
    </form>
    <form action="/vehiclemake/createvehiclemake" method="post">
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>

    </div>

Views/VehicleMake/UpdateManufacturer.cshtml
@model monozd.Models.VehicleMake
@{
    ViewData["Title"] = "UpdateVehicleManufacturer";
    VehicleMake maker = TempData["manufacturerDb"] as VehicleMake;
}

    <h1>Update Maker</h1>


    <div class ="contianer">
        <div asp-validation-summary="All"></div>

        <form action="/VehicleMake/UpdateManufacturerFinal" method="post">
            <input type="hidden" asp-for="Id" value="@maker.Id"/>        
        <div class="form-group">
            <label>Name</label>
            <input type="Name" placeholder="Enter manufacturer's name " asp-for="Name" value="@maker.Name">
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label>Abrv</label>
            <input type="Abrv" placeholder="Enter manufacturer's abrivation " asp-for="Abrv" value="@maker.Abrv">
            <span asp-validation-for="Abrv" class="text-danger"></span>
        </div>
        
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
        </div>

Views/VehicleModel/CreateVehicleModel.cshtml
@model monozd.Models.VehicleModel
@{
    ViewData["Title"] = "CreateVehicleModel";

    List<VehicleModel> modelsData  = TempData["models"] as List<VehicleModel>;

}

    <div class ="contianer">
    <form from action="/vehiclemodel/CreateVehicleModel" method="post">
        <div class="form-group">
            <label>MakeId</label>
            <input type="MakeId" placeholder="Enter Manufacturer's ID " asp-for="MakeId">
            <span asp-validation-for="MakeId" class="text-danger"></span>

        </div>
        <div class="form-group">
            <label>Name</label>
            <input type="Name" placeholder="Enter car's name " asp-for="Name">
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label>Abrv</label>
            <input type="Abrv" placeholder="Enter model's abrivation " asp-for="Abrv">
            <span asp-validation-for="Abrv" class="text-danger"></span>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    </div>
    
    <div class="container">

        @if(modelsData != null && modelsData.Count >= 1)
        {

        <form from action="/VehicleModel/SearchModel" method="post">
            <div class="form-group">
                <label>Search</label>
                <input type="text" name="searchTerm"/>
            </div> 
            <button type="submit" class="btn btn-primary">Search</button>
        </form>      
            <table class="table table-dark">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">MakeId</th>
      <th scope="col">Name</th>
      <th scope="col">Abrv</th>
    </tr>
  </thead>
  <tbody>
      @foreach (var models in modelsData)
      {
        <tr>
      <td>@models.Id</td>
      <td>@models.MakeId</td>
      <td>@models.Name</td>
      <td>@models.Abrv</td>
       <td>
          <form asp-action="UpdateModel" asp-controller="VehicleModel" method="post">
              <input type="hidden" asp-for="Id" value="@models.Id" />
              <button type="submit"  class="btn btn-success">Update</button>
          </form>
          <form asp-action="DeletePost" asp-controller="VehicleModel" method="post">
              <input type="hidden" asp-for="Id" value="@models.Id" />
              <button type="Delete" class="btn btn-danger">Delete</button>
          </form>
      </td>     
    </tr>
      }
    
  </tbody>
</table>
        }
    </div>
    

Views/VehicleModel/DeletePost.cshtml
@model monozd.Models.VehicleModel
@{
    ViewData["Title"] = "DeleteModel";
    VehicleModel models = TempData["models"] as VehicleModel;

}

<h1>Delete Manufacturer</h1>

    <div class="container">
    <form asp-action="DeletePost" method="post" asp-controllesr="VehicleModel" >
    <input type ="hidden" asp-for="Id" value="@models.Id" />
        <button type="submit" class="btn btn-danger">Delete</button>
    </form>
    <form action="/vehiclemake/createvehiclemake" method="post">
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>

    </div>

Views/VehicleModel/UpdateModel.cshtml
@model monozd.Models.VehicleModel
@{
    ViewData["Title"] = "UpdateVehicleModel";
    VehicleModel modelValue = TempData["modelDb"] as VehicleModel;
}

    <div class ="contianer">
        <div asp-validation-summary="All"></div>

        <form action="/vehiclemodel/UpdateModelFinal" method="post">
            <input type="hidden" asp-for="Id" value="@modelValue.Id"/>

        <div class="form-group">
                <label>MakeId</label>
            <input type="MakeId" placeholder="Enter Manufacturer's ID " asp-for="MakeId" value="@modelValue.MakeId"> 
            <span asp-validation-for="MakeId" class="text-danger"></span>

        </div>
        
        <div class="form-group">
            <label>Name</label>
            <input type="Name" placeholder="Enter car's name " asp-for="Name" value="@modelValue.Name">
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label>Abrv</label>
            <input type="Abrv" placeholder="Enter model's abrivation " asp-for="Abrv" value="@modelValue.Abrv">
            <span asp-validation-for="Abrv" class="text-danger"></span>
        </div>
        
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    </div>